# Generated by Django 3.2 on 2021-04-24 02:51

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "해당 사용자 이름은 이미 존재합니다."},
                help_text="150자 이하 문자, 숫자 그리고 @/./+/-/_만 가능합니다.",
                max_length=20,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="사용자 이름",
            ),
        ),
    ]
