# Generated by Django 3.2 on 2021-04-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="게시판 상세 설명"),
        ),
    ]
