# Generated by Django 3.2 on 2021-04-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
    ]
