# Generated by Django 3.2 on 2021-04-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_post_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='삭제'),
        ),
    ]
